.Dd February 17, 2018
.Dt M3UTILS 7
.Os
.Sh NAME
.Nm m3utils
.Nd introduction to the m3utils media file utilities
.Sh DESCRIPTION
.Nm
is a set of Unix utilities to manage media files.
.Pp
.Bl -tag -width 11n -compact
.It Xr m3grep 1
search media files matching a pattern
.It Xr m3print 1
print tags of media files
.It Xr m3sort 1
sort media files
.El
